Implemented React Frontend for places dataset marketplace and playground
abdullahalhoothy/s_locator pull request #1
Opened 2024-05-25 15:05 UTC by AbdulBasitKhaleeq

Implemented React Frontend for places dataset marketplace and playground

2024-05-25 15:46 UTC, abdullahalhoothy requested changes
Please see all the comments

2024-05-25 15:46 UTC, abdullahalhoothy commented on FrontEnd/src/App.test.tsx
The name of this file is app.test.
is this only for testing purposes? if yes and if you've already done the test just put it in a separate test directory

2024-05-25 15:46 UTC, abdullahalhoothy commented on FrontEnd/src/pages/Dataview/Dataview.tsx
> +const Dataview: React.FC = () => {
And this function your hard coding what is going to be gotten from the API but what if the API doesn't return some of these fields the whole thing is going to crash right?
Can you redo this to make it a bit more dynamic so that it expects at least required only the address everything else is optional ? Because I'm thinking about changing what the API will deliver to the website except for the location

2024-05-25 15:46 UTC, abdullahalhoothy commented on FrontEnd/src/pages/Dataview/Dataview.tsx
> +    const fetchBusinessData = async () => {
why is there hard coding values in this section?
          lat: 22.4925,
          lng: 39.17757,
          radius: 5000,
          type: "grocery_or_supermarket",

2024-05-25 15:46 UTC, abdullahalhoothy commented on FrontEnd/src/pages/Home/Home.tsx
> +mapboxgl.accessToken =
You should remove the map box access token that you have down there
And make stuff like this load from a JSON module
So I do not want to put my API key directly into the .tsx code , i want it to be in a separate config file "api_keys.config" for example

2024-05-25 15:46 UTC, abdullahalhoothy commented on FrontEnd/src/pages/Home/Home.tsx
> +          const data1 = await fetchBusinesses({
same question as previous file , why are these values hard coded into the .tsx file?
This data that's coming from the JSON file is dynamic the user can put any data so why is there any hard coding at all?

2024-05-25 15:46 UTC, abdullahalhoothy commented on FrontEnd/src/services/apiService.ts
> +let baseUrl = 'localhost:8000';
This needs to be in a separate configuration file.
The file should contain all the Urls all these information
for example "common_urls.json" 
let baseUrl = 'localhost:8000';

2024-05-25 15:46 UTC, abdullahalhoothy commented on FrontEnd/src/services/apiService.ts
> + * @returns
Is this something you still have to do?
Or is this something that you're requesting of me to do in the middle api?

2024-05-25 15:46 UTC, abdullahalhoothy commented on FrontEnd/src/services/apiService.ts
> +                    },
we need to talk about this

2024-05-25 15:46 UTC, abdullahalhoothy commented on FrontEnd/src/setupTests.ts
If this is just for testing purposes then separated into a different test folder or something like that

2024-05-25 15:49 UTC, AbdulBasitKhaleeq commented on FrontEnd/src/setupTests.ts
it is an auto generated file, can remove it.

2024-05-25 15:50 UTC, AbdulBasitKhaleeq commented on FrontEnd/src/services/apiService.ts
> +                    },
sure

2024-05-25 15:51 UTC, AbdulBasitKhaleeq commented on FrontEnd/src/services/apiService.ts
> + * @returns
as there is not api for requestion available data catalog I created a wrapper function for it, you just have to uncomment the client.get code and remove the hardcoded json

2024-05-25 15:52 UTC, AbdulBasitKhaleeq commented on FrontEnd/src/services/apiService.ts
> +let baseUrl = 'localhost:8000';
sure

2024-05-25 15:55 UTC, AbdulBasitKhaleeq commented on FrontEnd/src/pages/Home/Home.tsx
> +          const data1 = await fetchBusinesses({
once the catalog api is created and integrated, on selection of catalog item we will be questing for dataset based on data available in catalog object. right now catalog API is not there and there is one sample dataset request payload you shared so I added it here as hardcoded.

2024-05-25 15:55 UTC, AbdulBasitKhaleeq commented on FrontEnd/src/pages/Home/Home.tsx
> +mapboxgl.accessToken =
sure

2024-05-25 15:55 UTC, AbdulBasitKhaleeq commented on FrontEnd/src/pages/Dataview/Dataview.tsx
> +    const fetchBusinessData = async () => {
once the catalog api is created and integrated, on selection of catalog item we will be questing for dataset based on data available in catalog object. right now catalog API is not there and there is one sample dataset request payload you shared so I added it here as hardcoded.

2024-05-25 15:57 UTC, AbdulBasitKhaleeq commented on FrontEnd/src/pages/Dataview/Dataview.tsx
> +const Dataview: React.FC = () => {
empty values will be shown if data is not there, also added null checks. there is an interface defined, if you are changing something you have to update it accordingly.

2024-05-25 15:58 UTC, AbdulBasitKhaleeq commented on FrontEnd/src/App.test.tsx
it is an auto generated file, can be removed.

2024-05-26 09:18 UTC, AbdulBasitKhaleeq commented on FrontEnd/src/pages/Home/Home.tsx
> +mapboxgl.accessToken =
done

2024-05-26 19:30 UTC, abdullahalhoothy requested changes
the reason for the error is that you are sending to get the catalogue data to the wrong endpoint , there is a new websocket endpoint

2024-05-26 19:30 UTC, abdullahalhoothy commented on FrontEnd/.env
> +REACT_APP_MAPBOX_KEY=pk.eyJ1IjoidWhhaWRlcjE0IiwiYSI6ImNsdHg5Y3F1MjAwa28ybG02a3AyajZoNnEifQ.Gz8HFmZK8UwXW3dTsSQ1Uw
please add here the other Urls for the catalogue and dataset

2024-05-26 19:30 UTC, abdullahalhoothy commented on FrontEnd/src/services/apiService.ts
> +        const response = await apiClient.post('/request_dataset_load', jsonData);
This must not be hardcoded here , please move it with the other URLS

2024-05-26 19:30 UTC, abdullahalhoothy commented on FrontEnd/src/services/apiService.ts
> +        const websocket = new WebSocket(`${webSocketURL}${requestId}`);
This is why you are getting the error , 
because i didn't do the frontend side this time , and because Fastapi doesn't provide auto documentation for websockets , you didn't know the new websocket URL
these are the 5 endpoints
    "fetch_data_url": "http://localhost:8000/fetch-data",
    "metadata_url": "http://localhost:8000/get_catalogue_metadata",
    "data_load_url": "http://localhost:8000/request_dataset_load",
    "websocket_url": "ws://localhost:8000/ws/",
    "websocket_load_catalogue_dataset_url": "ws://localhost:8000/ws_dataset_load/"

2024-05-26 19:30 UTC, abdullahalhoothy commented on FrontEnd/src/services/apiService.ts
> +export const fetchBusinessesOld = async (jsonData: {
```suggestion
export const fetchSinglePointData= async (jsonData: {
```

2024-05-26 19:30 UTC, abdullahalhoothy commented on FrontEnd/.env
> +REACT_APP_MAPBOX_KEY=pk.eyJ1IjoidWhhaWRlcjE0IiwiYSI6ImNsdHg5Y3F1MjAwa28ybG02a3AyajZoNnEifQ.Gz8HFmZK8UwXW3dTsSQ1Uw
"fetch_data_url": "http://localhost:8000/fetch-data",
"metadata_url": "http://localhost:8000/get_catalogue_metadata",
"data_load_url": "http://localhost:8000/request_dataset_load",
"websocket_url": "ws://localhost:8000/ws/",
"websocket_load_catalogue_dataset_url": "ws://localhost:8000/ws_dataset_load/"

2024-05-26 19:57 UTC, AbdulBasitKhaleeq commented on FrontEnd/.env
> +REACT_APP_MAPBOX_KEY=pk.eyJ1IjoidWhhaWRlcjE0IiwiYSI6ImNsdHg5Y3F1MjAwa28ybG02a3AyajZoNnEifQ.Gz8HFmZK8UwXW3dTsSQ1Uw
only base urls for API will go in .env

2024-05-26 19:57 UTC, AbdulBasitKhaleeq commented on FrontEnd/src/services/apiService.ts
> +        const response = await apiClient.post('/request_dataset_load', jsonData);
urls are always added in code. 1000s of urls we do not keep them in .env files

2024-05-26 19:58 UTC, AbdulBasitKhaleeq commented on FrontEnd/src/services/apiService.ts
> +        const websocket = new WebSocket(`${webSocketURL}${requestId}`);
recent Backend changes effected the urls

2024-05-26 19:59 UTC, AbdulBasitKhaleeq commented on FrontEnd/src/services/apiService.ts
> +export const fetchBusinessesOld = async (jsonData: {
not is ues, kept for reference if you need in future

2024-05-26 20:02 UTC, abdullahalhoothy commented on FrontEnd/.env
> +REACT_APP_MAPBOX_KEY=pk.eyJ1IjoidWhhaWRlcjE0IiwiYSI6ImNsdHg5Y3F1MjAwa28ybG02a3AyajZoNnEifQ.Gz8HFmZK8UwXW3dTsSQ1Uw
okay You can keep the base url in the env but all the other urls need to be in a different config file
Because in the future I will change the urls
this is just urls for development.

2024-05-28 23:45 UTC, abdullahalhoothy approved these changes

2024-05-28 23:46 UTC, merged