by Ak
abdullahalhoothy/s_locator pull request #10
Opened 2024-09-21 19:40 UTC by y-u-m-iy-u-m-i

2024-09-21 22:25 UTC, abdullahalhoothy requested changes

2024-09-21 22:25 UTC, abdullahalhoothy commented on .github/workflows/ci-cd.yml
> +          fi
please isolate this in a seperate file instead of inline script

2024-09-21 22:25 UTC, abdullahalhoothy commented on .github/workflows/ci-cd.yml
> +          docker compose up -d
shouldn't this be "docker-compose" ?

2024-09-21 22:25 UTC, abdullahalhoothy commented on 123secrets_variables.json
> +    "PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED": "False"
this is correct to be False? didn't we say we need password?

2024-09-21 22:37 UTC, ahmed-kamal2004 commented on .github/workflows/ci-cd.yml
> +          docker compose up -d
docker-compose is an old version written in python, so it causes problems with env variables
While docker compose is newer and it doesn't have problems
i tested both of them.

2024-09-21 22:38 UTC, ahmed-kamal2004 commented on .github/workflows/ci-cd.yml
> +          docker compose up -d
docker compose is also a plugin for docker written in go

2024-09-21 22:39 UTC, ahmed-kamal2004 commented on 123secrets_variables.json
> +    "PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED": "False"
Yes I made it true for
PGADMIN_CONFIG_SERVER_MODE
But for PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED
It is another thing about a master password for initialization

Now the pgadmin is configured as we  talked

2024-09-21 22:40 UTC, ahmed-kamal2004 commented on .github/workflows/ci-cd.yml
> +          fi
Ok

2024-09-23 18:23 UTC, abdullahalhoothy approved these changes

2024-09-23 18:23 UTC, merged